### ISSUE TITLE
Class 'Invitations' not found

### ISSUE THREAD

**Issue by SrPatinhas** [Atbox/invi-l5#2]
After i try to run `php artisan migrate` it returns this error:

```
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Invitations' not found
```

Any help you can give? its a fresh install.

**Comment by sajjadrad** [comment]
Please remove `database\migrations\2014_02_28_192137_invitations.php` file and run publish command again:

`php artisan vendor:publish`

Thank you
