### ISSUE TITLE
Having issues on artisan migrate

### ISSUE THREAD

**Issue by hindermyertim** [Atbox/invi-l5#3]
Hi,

I'm on Laravel 5.2 and I'm having some issues with this on the artisan migrate.

vagrant@leftrite:~/leftrite$ php artisan vendor:publish
Copied Directory [/vendor/atbox/invi/src/migrations] To [/database/migrations]
Publishing complete for tag []!
vagrant@leftrite:~/leftrite$ php artisan migrate

  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Fatal error: Class 'Invitations' not found

Let me know if you have any ideas or if this isn't supported for 5.2

Thanks

**Comment by sajjadrad** [comment]
@hindermyertim Please remove invitation migration file (2014_02_28_192137_invitations.php) from database/migrations directory and update composer again, then follow install steps again, if there was some problems run `composer dump-autoload -o`. let me know if it works.

Thanks

**Comment by hindermyertim** [comment]
Thanks for getting back to me so fast!

I went through the steps again and it worked this time! I have no idea why it did now, and not the other 3 or 4 attempts but hey I'm not complaining.

Cheers,
Tim
